services:
  - type: web
    name: isrbackend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    buildCommand: npm install && npm build
    healthCheckPath: /_health
    disk:
      name: isrbackend-uploads
      mountPath: /opt/render/project/src/public/uploads
      sizeGB: 1
    envVars:
      - key: NODE_VERSION
        value: 22.9
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: isrbackend
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true

databases:
  - name: isrbackend
    plan: free